/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const AccountIdentifier = IDL.Vec(IDL.Nat8);
export const Tokens = IDL.Nat;
export const TransferResult = IDL.Variant({
  'ok' : IDL.Record({ 'amount' : Tokens }),
  'err' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DepositAccountView = IDL.Record({
  'accountId' : AccountIdentifier,
  'canisterId' : IDL.Principal,
});
export const HouseStats = IDL.Record({
  'totalWagered' : Tokens,
  'totalPaidOut' : Tokens,
  'totalSpins' : IDL.Nat,
  'houseRetained' : Tokens,
  'houseBalance' : Tokens,
});
export const UserId = IDL.Principal;
export const PlayerView = IDL.Record({ 'id' : UserId, 'balance' : Tokens });
export const Timestamp = IDL.Nat;
export const Symbol = IDL.Variant({
  'bar' : IDL.Null,
  'bell' : IDL.Null,
  'star' : IDL.Null,
  'diamond' : IDL.Null,
  'horseshoe' : IDL.Null,
  'lemon' : IDL.Null,
  'seven' : IDL.Null,
  'cherry' : IDL.Null,
});
export const ReelGrid = IDL.Vec(IDL.Vec(Symbol));
export const SpinRecord = IDL.Record({
  'id' : IDL.Nat,
  'won' : IDL.Bool,
  'winningLines' : IDL.Vec(IDL.Nat),
  'timestamp' : Timestamp,
  'wager' : Tokens,
  'activeLines' : IDL.Nat,
  'reels' : ReelGrid,
  'payout' : Tokens,
});
export const TxKind = IDL.Variant({
  'win' : IDL.Null,
  'spinCost' : IDL.Null,
  'transferOut' : IDL.Null,
  'transferIn' : IDL.Null,
  'adminTransferOut' : IDL.Null,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'kind' : TxKind,
  'counterparty' : IDL.Opt(AccountIdentifier),
  'timestamp' : Timestamp,
  'amount' : Tokens,
});
export const SpinOutcome = IDL.Record({
  'won' : IDL.Bool,
  'winningLines' : IDL.Vec(IDL.Nat),
  'wager' : Tokens,
  'activeLines' : IDL.Nat,
  'reels' : ReelGrid,
  'payout' : Tokens,
});
export const SyncDepositResult = IDL.Record({
  'balance' : Tokens,
  'credited' : Tokens,
});

export const idlService = IDL.Service({
  '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
  '__aggregateStats' : IDL.Func([], [IDL.Reserved], ['query']),
  '__counters' : IDL.Func([], [IDL.Reserved], ['query']),
  '__houseBalance' : IDL.Func([], [IDL.Reserved], ['query']),
  '__players' : IDL.Func([], [IDL.Reserved], ['query']),
  '__spinHistory' : IDL.Func([], [IDL.Reserved], ['query']),
  '__transactions' : IDL.Func([], [IDL.Reserved], ['query']),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'adminTransfer' : IDL.Func([AccountIdentifier, Tokens], [TransferResult], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getBalance' : IDL.Func([], [Tokens], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDepositAccount' : IDL.Func([], [DepositAccountView], ['query']),
  'getHouseBalance' : IDL.Func([], [Tokens], ['query']),
  'getHouseDepositAccount' : IDL.Func([], [DepositAccountView], ['query']),
  'getHouseStats' : IDL.Func([], [HouseStats], ['query']),
  'getOrCreatePlayer' : IDL.Func([], [PlayerView], []),
  'getSpinHistory' : IDL.Func([], [IDL.Vec(SpinRecord)], ['query']),
  'getTransactionHistory' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'spin' : IDL.Func([IDL.Nat], [SpinOutcome], []),
  'syncDeposit' : IDL.Func([], [SyncDepositResult], []),
  'transfer' : IDL.Func([AccountIdentifier, Tokens], [TransferResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const AccountIdentifier = IDL.Vec(IDL.Nat8);
  const Tokens = IDL.Nat;
  const TransferResult = IDL.Variant({
    'ok' : IDL.Record({ 'amount' : Tokens }),
    'err' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DepositAccountView = IDL.Record({
    'accountId' : AccountIdentifier,
    'canisterId' : IDL.Principal,
  });
  const HouseStats = IDL.Record({
    'totalWagered' : Tokens,
    'totalPaidOut' : Tokens,
    'totalSpins' : IDL.Nat,
    'houseRetained' : Tokens,
    'houseBalance' : Tokens,
  });
  const UserId = IDL.Principal;
  const PlayerView = IDL.Record({ 'id' : UserId, 'balance' : Tokens });
  const Timestamp = IDL.Nat;
  const Symbol = IDL.Variant({
    'bar' : IDL.Null,
    'bell' : IDL.Null,
    'star' : IDL.Null,
    'diamond' : IDL.Null,
    'horseshoe' : IDL.Null,
    'lemon' : IDL.Null,
    'seven' : IDL.Null,
    'cherry' : IDL.Null,
  });
  const ReelGrid = IDL.Vec(IDL.Vec(Symbol));
  const SpinRecord = IDL.Record({
    'id' : IDL.Nat,
    'won' : IDL.Bool,
    'winningLines' : IDL.Vec(IDL.Nat),
    'timestamp' : Timestamp,
    'wager' : Tokens,
    'activeLines' : IDL.Nat,
    'reels' : ReelGrid,
    'payout' : Tokens,
  });
  const TxKind = IDL.Variant({
    'win' : IDL.Null,
    'spinCost' : IDL.Null,
    'transferOut' : IDL.Null,
    'transferIn' : IDL.Null,
    'adminTransferOut' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'kind' : TxKind,
    'counterparty' : IDL.Opt(AccountIdentifier),
    'timestamp' : Timestamp,
    'amount' : Tokens,
  });
  const SpinOutcome = IDL.Record({
    'won' : IDL.Bool,
    'winningLines' : IDL.Vec(IDL.Nat),
    'wager' : Tokens,
    'activeLines' : IDL.Nat,
    'reels' : ReelGrid,
    'payout' : Tokens,
  });
  const SyncDepositResult = IDL.Record({
    'balance' : Tokens,
    'credited' : Tokens,
  });
  
  return IDL.Service({
    '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
    '__aggregateStats' : IDL.Func([], [IDL.Reserved], ['query']),
    '__counters' : IDL.Func([], [IDL.Reserved], ['query']),
    '__houseBalance' : IDL.Func([], [IDL.Reserved], ['query']),
    '__players' : IDL.Func([], [IDL.Reserved], ['query']),
    '__spinHistory' : IDL.Func([], [IDL.Reserved], ['query']),
    '__transactions' : IDL.Func([], [IDL.Reserved], ['query']),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'adminTransfer' : IDL.Func(
        [AccountIdentifier, Tokens],
        [TransferResult],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getBalance' : IDL.Func([], [Tokens], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDepositAccount' : IDL.Func([], [DepositAccountView], ['query']),
    'getHouseBalance' : IDL.Func([], [Tokens], ['query']),
    'getHouseDepositAccount' : IDL.Func([], [DepositAccountView], ['query']),
    'getHouseStats' : IDL.Func([], [HouseStats], ['query']),
    'getOrCreatePlayer' : IDL.Func([], [PlayerView], []),
    'getSpinHistory' : IDL.Func([], [IDL.Vec(SpinRecord)], ['query']),
    'getTransactionHistory' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'spin' : IDL.Func([IDL.Nat], [SpinOutcome], []),
    'syncDeposit' : IDL.Func([], [SyncDepositResult], []),
    'transfer' : IDL.Func([AccountIdentifier, Tokens], [TransferResult], []),
  });
};

export const init = ({ IDL }) => { return []; };