/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AccountIdentifier = Uint8Array;
export interface DepositAccountView {
  'legacyAccountId' : [] | [AccountIdentifier],
  'accountId' : AccountIdentifier,
  'canisterId' : Principal,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface HouseStats {
  'totalWagered' : Tokens,
  'totalPaidOut' : Tokens,
  'totalSpins' : bigint,
  'houseRetained' : Tokens,
  'houseBalance' : Tokens,
}
export interface PlayerView { 'id' : UserId, 'balance' : Tokens }
export type ReelGrid = Array<Array<Symbol>>;
export type Result = { 'ok' : null } |
  { 'err' : Error };
export interface SpinOutcome {
  'won' : boolean,
  'betMultiplier' : bigint,
  'winningLines' : Array<bigint>,
  'wager' : Tokens,
  'activeLines' : bigint,
  'reels' : ReelGrid,
  'payout' : Tokens,
}
export interface SpinRecord {
  'id' : bigint,
  'won' : boolean,
  'betMultiplier' : bigint,
  'winningLines' : Array<bigint>,
  'timestamp' : Timestamp,
  'wager' : Tokens,
  'activeLines' : bigint,
  'reels' : ReelGrid,
  'payout' : Tokens,
}
export type SpinResult = { 'ok' : SpinOutcome } |
  { 'err' : string };
export type Symbol = { 'bar' : null } |
  { 'bell' : null } |
  { 'star' : null } |
  { 'diamond' : null } |
  { 'horseshoe' : null } |
  { 'lemon' : null } |
  { 'seven' : null } |
  { 'cherry' : null };
export interface SyncDepositResult {
  'warning' : [] | [string],
  'balance' : Tokens,
  'ledgerDefault' : Tokens,
  'ledgerHouse' : Tokens,
  'credited' : Tokens,
}
export type Timestamp = bigint;
export type Tokens = bigint;
export interface Transaction {
  'id' : bigint,
  'kind' : TxKind,
  'counterparty' : [] | [AccountIdentifier],
  'timestamp' : Timestamp,
  'amount' : Tokens,
}
export type TransferResult = {
    'ok' : { 'fee' : Tokens, 'blockIndex' : bigint, 'amount' : Tokens }
  } |
  { 'err' : string };
export type TxKind = { 'win' : null } |
  { 'spinCost' : null } |
  { 'transferOut' : null } |
  { 'transferIn' : null } |
  { 'adminTransferOut' : null };
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '__accessControlState' : ActorMethod<[], any>,
  '__aggregateStats' : ActorMethod<[], any>,
  '__counters' : ActorMethod<[], any>,
  '__houseBalance' : ActorMethod<[], any>,
  '__players' : ActorMethod<[], any>,
  '__spinHistory' : ActorMethod<[], any>,
  '__transactions' : ActorMethod<[], any>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'adminTransfer' : ActorMethod<[AccountIdentifier, Tokens], TransferResult>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getBalance' : ActorMethod<[], Tokens>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDepositAccount' : ActorMethod<[], DepositAccountView>,
  'getHouseBalance' : ActorMethod<[], Tokens>,
  'getHouseDepositAccount' : ActorMethod<[], DepositAccountView>,
  'getHouseStats' : ActorMethod<[], HouseStats>,
  'getOrCreatePlayer' : ActorMethod<[], PlayerView>,
  'getSpinHistory' : ActorMethod<[], Array<SpinRecord>>,
  'getTransactionHistory' : ActorMethod<[], Array<Transaction>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'spin' : ActorMethod<[bigint, bigint], SpinResult>,
  'syncDeposit' : ActorMethod<[], SyncDepositResult>,
  'syncHouseDeposit' : ActorMethod<[], SyncDepositResult>,
  'transfer' : ActorMethod<[AccountIdentifier, Tokens], TransferResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];